// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WordWave.Infrastructure.Data;

#nullable disable

namespace WordWave.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WordWave.Domain.Models.GrammarExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("En")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("en");

                    b.Property<int?>("GrammarLessonId")
                        .HasColumnType("integer");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Vi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vi");

                    b.HasKey("Id");

                    b.HasIndex("GrammarLessonId");

                    b.ToTable("grammar_examples", (string)null);
                });

            modelBuilder.Entity("WordWave.Domain.Models.GrammarLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formula");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Tips")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tips");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("grammar_lessons", (string)null);
                });

            modelBuilder.Entity("WordWave.Domain.Models.SentencePattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string[]>("Examples")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("examples");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sentence");

                    b.HasKey("Id");

                    b.ToTable("sentence_patterns", (string)null);
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("ToeicQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("toeic_question_id");

                    b.HasKey("Id");

                    b.HasIndex("ToeicQuestionId");

                    b.ToTable("toeic_answers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerText = "A man is placing a laptop on a table.",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnswerText = "A woman is watering plants.",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            AnswerText = "The chairs are being stacked.",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            AnswerText = "The lights are being repaired.",
                            IsCorrect = false,
                            Label = "D",
                            ToeicQuestionId = 1
                        },
                        new
                        {
                            Id = 5,
                            AnswerText = "People are waiting near an elevator.",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            AnswerText = "A truck is leaving a warehouse.",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            AnswerText = "A document is being printed.",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 2
                        },
                        new
                        {
                            Id = 8,
                            AnswerText = "A meal is being served.",
                            IsCorrect = false,
                            Label = "D",
                            ToeicQuestionId = 2
                        },
                        new
                        {
                            Id = 9,
                            AnswerText = "It should be here by noon.",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            AnswerText = "At the loading dock.",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 3
                        },
                        new
                        {
                            Id = 11,
                            AnswerText = "Because it was expensive.",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 3
                        },
                        new
                        {
                            Id = 12,
                            AnswerText = "The marketing team did.",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 4
                        },
                        new
                        {
                            Id = 13,
                            AnswerText = "For about thirty minutes.",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 4
                        },
                        new
                        {
                            Id = 14,
                            AnswerText = "On the second floor.",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 4
                        },
                        new
                        {
                            Id = 15,
                            AnswerText = "She has a client call at the original time.",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 5
                        },
                        new
                        {
                            Id = 16,
                            AnswerText = "She lost the meeting notes.",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 5
                        },
                        new
                        {
                            Id = 17,
                            AnswerText = "She is traveling to another city.",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 5
                        },
                        new
                        {
                            Id = 18,
                            AnswerText = "Update the calendar invitation.",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 6
                        },
                        new
                        {
                            Id = 19,
                            AnswerText = "Cancel the project.",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 6
                        },
                        new
                        {
                            Id = 20,
                            AnswerText = "Print the sales report.",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 6
                        },
                        new
                        {
                            Id = 21,
                            AnswerText = "To announce a schedule change.",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 7
                        },
                        new
                        {
                            Id = 22,
                            AnswerText = "To introduce a new employee.",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 7
                        },
                        new
                        {
                            Id = 23,
                            AnswerText = "To advertise a product.",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 7
                        },
                        new
                        {
                            Id = 24,
                            AnswerText = "In the north lot.",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 8
                        },
                        new
                        {
                            Id = 25,
                            AnswerText = "Beside the cafeteria.",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 8
                        },
                        new
                        {
                            Id = 26,
                            AnswerText = "At the visitor desk.",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 8
                        },
                        new
                        {
                            Id = 27,
                            AnswerText = "by",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 9
                        },
                        new
                        {
                            Id = 28,
                            AnswerText = "among",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 9
                        },
                        new
                        {
                            Id = 29,
                            AnswerText = "during",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 9
                        },
                        new
                        {
                            Id = 30,
                            AnswerText = "training",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 10
                        },
                        new
                        {
                            Id = 31,
                            AnswerText = "trained",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 10
                        },
                        new
                        {
                            Id = 32,
                            AnswerText = "train",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 10
                        },
                        new
                        {
                            Id = 33,
                            AnswerText = "ID cards",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 11
                        },
                        new
                        {
                            Id = 34,
                            AnswerText = "laptops",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 11
                        },
                        new
                        {
                            Id = 35,
                            AnswerText = "receipts",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 11
                        },
                        new
                        {
                            Id = 36,
                            AnswerText = "a safety training session",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 12
                        },
                        new
                        {
                            Id = 37,
                            AnswerText = "a company picnic",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 12
                        },
                        new
                        {
                            Id = 38,
                            AnswerText = "a hiring announcement",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 12
                        },
                        new
                        {
                            Id = 39,
                            AnswerText = "For maintenance.",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 13
                        },
                        new
                        {
                            Id = 40,
                            AnswerText = "For a delivery.",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 13
                        },
                        new
                        {
                            Id = 41,
                            AnswerText = "For a staff meeting.",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 13
                        },
                        new
                        {
                            Id = 42,
                            AnswerText = "The cafeteria entrance.",
                            IsCorrect = true,
                            Label = "A",
                            ToeicQuestionId = 14
                        },
                        new
                        {
                            Id = 43,
                            AnswerText = "The lobby entrance.",
                            IsCorrect = false,
                            Label = "B",
                            ToeicQuestionId = 14
                        },
                        new
                        {
                            Id = 44,
                            AnswerText = "The parking garage entrance.",
                            IsCorrect = false,
                            Label = "C",
                            ToeicQuestionId = 14
                        });
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicAudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("local_path");

                    b.Property<int>("ToeicPartId")
                        .HasColumnType("integer")
                        .HasColumnName("toeic_part_id");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transcript");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ToeicPartId");

                    b.ToTable("toeic_audios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalPath = "",
                            ToeicPartId = 1,
                            Transcript = "A man is placing a laptop on a table.",
                            Url = "https://example.com/audio/toeic-part1-sample.mp3"
                        },
                        new
                        {
                            Id = 2,
                            LocalPath = "",
                            ToeicPartId = 2,
                            Transcript = "When will the shipment arrive?",
                            Url = "https://example.com/audio/toeic-part2-sample.mp3"
                        },
                        new
                        {
                            Id = 3,
                            LocalPath = "",
                            ToeicPartId = 3,
                            Transcript = "Two coworkers discuss moving a client meeting to Thursday.",
                            Url = "https://example.com/audio/toeic-part3-sample.mp3"
                        },
                        new
                        {
                            Id = 4,
                            LocalPath = "",
                            ToeicPartId = 4,
                            Transcript = "A manager announces a change to the office schedule.",
                            Url = "https://example.com/audio/toeic-part4-sample.mp3"
                        });
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("FailedItems")
                        .HasColumnType("integer")
                        .HasColumnName("failed_items");

                    b.Property<int>("ImportedItems")
                        .HasColumnType("integer")
                        .HasColumnName("imported_items");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.HasKey("Id");

                    b.ToTable("toeic_import_logs", (string)null);
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int>("PartNumber")
                        .HasColumnType("integer")
                        .HasColumnName("part_number");

                    b.Property<int>("ToeicTestId")
                        .HasColumnType("integer")
                        .HasColumnName("toeic_test_id");

                    b.HasKey("Id");

                    b.HasIndex("ToeicTestId");

                    b.ToTable("toeic_parts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Instructions = "Choose the sentence that best describes the picture.",
                            Name = "Picture Description",
                            OrderIndex = 1,
                            PartNumber = 1,
                            ToeicTestId = 1
                        },
                        new
                        {
                            Id = 2,
                            Instructions = "Choose the best response to each question.",
                            Name = "Question Response",
                            OrderIndex = 2,
                            PartNumber = 2,
                            ToeicTestId = 1
                        },
                        new
                        {
                            Id = 3,
                            Instructions = "Listen to each conversation and answer the questions.",
                            Name = "Conversations",
                            OrderIndex = 3,
                            PartNumber = 3,
                            ToeicTestId = 1
                        },
                        new
                        {
                            Id = 4,
                            Instructions = "Listen to each talk and answer the questions.",
                            Name = "Talks",
                            OrderIndex = 4,
                            PartNumber = 4,
                            ToeicTestId = 1
                        },
                        new
                        {
                            Id = 5,
                            Instructions = "Choose the word or phrase that best completes the sentence.",
                            Name = "Incomplete Sentences",
                            OrderIndex = 5,
                            PartNumber = 5,
                            ToeicTestId = 1
                        },
                        new
                        {
                            Id = 6,
                            Instructions = "Choose the best answer to complete the text.",
                            Name = "Text Completion",
                            OrderIndex = 6,
                            PartNumber = 6,
                            ToeicTestId = 1
                        },
                        new
                        {
                            Id = 7,
                            Instructions = "Read the text and answer the questions.",
                            Name = "Reading Comprehension",
                            OrderIndex = 7,
                            PartNumber = 7,
                            ToeicTestId = 1
                        });
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicPassage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("ToeicPartId")
                        .HasColumnType("integer")
                        .HasColumnName("toeic_part_id");

                    b.HasKey("Id");

                    b.HasIndex("ToeicPartId");

                    b.ToTable("toeic_passages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Please remember that the monthly safety training will begin at 9 a.m. in Conference Room B. Employees should bring their ID cards.",
                            Title = "Office Notice",
                            ToeicPartId = 6
                        },
                        new
                        {
                            Id = 2,
                            Content = "The west entrance will be closed on Friday for maintenance. Staff may use the lobby entrance or the parking garage entrance.",
                            Title = "Email from Facilities",
                            ToeicPartId = 7
                        });
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("question_number");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<int?>("ToeicAudioId")
                        .HasColumnType("integer")
                        .HasColumnName("toeic_audio_id");

                    b.Property<int>("ToeicPartId")
                        .HasColumnType("integer")
                        .HasColumnName("toeic_part_id");

                    b.Property<int?>("ToeicPassageId")
                        .HasColumnType("integer")
                        .HasColumnName("toeic_passage_id");

                    b.HasKey("Id");

                    b.HasIndex("ToeicAudioId");

                    b.HasIndex("ToeicPartId");

                    b.HasIndex("ToeicPassageId");

                    b.ToTable("toeic_questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "easy",
                            Explanation = "",
                            ImageUrl = "https://example.com/images/toeic-part1-desk.jpg",
                            Prompt = "Image: employee at desk",
                            QuestionNumber = 1,
                            QuestionText = "What is happening in the picture?",
                            ToeicAudioId = 1,
                            ToeicPartId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "easy",
                            Explanation = "",
                            ImageUrl = "https://example.com/images/toeic-part1-elevator.jpg",
                            Prompt = "Image: people near an elevator",
                            QuestionNumber = 2,
                            QuestionText = "What does the picture show?",
                            ToeicAudioId = 1,
                            ToeicPartId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "easy",
                            Explanation = "",
                            ImageUrl = "",
                            Prompt = "When will the shipment arrive?",
                            QuestionNumber = 3,
                            QuestionText = "Choose the best response.",
                            ToeicAudioId = 2,
                            ToeicPartId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "easy",
                            Explanation = "",
                            ImageUrl = "",
                            Prompt = "Who reserved the conference room?",
                            QuestionNumber = 4,
                            QuestionText = "Choose the best response.",
                            ToeicAudioId = 2,
                            ToeicPartId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "medium",
                            Explanation = "",
                            ImageUrl = "",
                            Prompt = "Conversation about a meeting",
                            QuestionNumber = 5,
                            QuestionText = "Why does the woman want to change the meeting time?",
                            ToeicAudioId = 3,
                            ToeicPartId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "medium",
                            Explanation = "",
                            ImageUrl = "",
                            Prompt = "Conversation about a meeting",
                            QuestionNumber = 6,
                            QuestionText = "What will the man probably do next?",
                            ToeicAudioId = 3,
                            ToeicPartId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "medium",
                            Explanation = "",
                            ImageUrl = "",
                            Prompt = "Announcement",
                            QuestionNumber = 7,
                            QuestionText = "What is the main purpose of the announcement?",
                            ToeicAudioId = 4,
                            ToeicPartId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "medium",
                            Explanation = "",
                            ImageUrl = "",
                            Prompt = "Announcement",
                            QuestionNumber = 8,
                            QuestionText = "Where should employees park tomorrow?",
                            ToeicAudioId = 4,
                            ToeicPartId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "easy",
                            Explanation = "",
                            ImageUrl = "",
                            Prompt = "",
                            QuestionNumber = 9,
                            QuestionText = "The report must be submitted _____ Friday afternoon.",
                            ToeicPartId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "easy",
                            Explanation = "",
                            ImageUrl = "",
                            Prompt = "",
                            QuestionNumber = 10,
                            QuestionText = "Ms. Carter is responsible for _____ the new interns.",
                            ToeicPartId = 5
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "easy",
                            Explanation = "",
                            ImageUrl = "",
                            Prompt = "",
                            QuestionNumber = 11,
                            QuestionText = "Employees should bring their _____ to the training.",
                            ToeicPartId = 6,
                            ToeicPassageId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "easy",
                            Explanation = "",
                            ImageUrl = "",
                            Prompt = "",
                            QuestionNumber = 12,
                            QuestionText = "The notice is mainly about _____.",
                            ToeicPartId = 6,
                            ToeicPassageId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "easy",
                            Explanation = "",
                            ImageUrl = "",
                            Prompt = "",
                            QuestionNumber = 13,
                            QuestionText = "Why will the west entrance be closed?",
                            ToeicPartId = 7,
                            ToeicPassageId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "easy",
                            Explanation = "",
                            ImageUrl = "",
                            Prompt = "",
                            QuestionNumber = 14,
                            QuestionText = "Which entrance is NOT mentioned as an alternative?",
                            ToeicPartId = 7,
                            ToeicPassageId = 2
                        });
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentOwner")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_owner");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("toeic_tests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentOwner = "WordWave",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Original sample mini test covering TOEIC parts 1 to 7.",
                            IsPublic = true,
                            License = "Internal sample content; do not treat as official TOEIC material.",
                            SourceName = "WordWave original sample",
                            SourceType = "seed",
                            SourceUrl = "",
                            Title = "WordWave TOEIC Mini Test"
                        });
                });

            modelBuilder.Entity("WordWave.Domain.Models.VocabWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("example");

                    b.Property<string>("ExampleMeaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("example_meaning");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Phonetic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phonetic");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.ToTable("vocabulary", (string)null);
                });

            modelBuilder.Entity("WordWave.Domain.Models.GrammarExample", b =>
                {
                    b.HasOne("WordWave.Domain.Models.GrammarLesson", null)
                        .WithMany("GrammarExamples")
                        .HasForeignKey("GrammarLessonId");
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicAnswer", b =>
                {
                    b.HasOne("WordWave.Domain.Models.ToeicQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("ToeicQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicAudio", b =>
                {
                    b.HasOne("WordWave.Domain.Models.ToeicPart", "Part")
                        .WithMany("Audios")
                        .HasForeignKey("ToeicPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicPart", b =>
                {
                    b.HasOne("WordWave.Domain.Models.ToeicTest", "Test")
                        .WithMany("Parts")
                        .HasForeignKey("ToeicTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicPassage", b =>
                {
                    b.HasOne("WordWave.Domain.Models.ToeicPart", "Part")
                        .WithMany("Passages")
                        .HasForeignKey("ToeicPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicQuestion", b =>
                {
                    b.HasOne("WordWave.Domain.Models.ToeicAudio", "Audio")
                        .WithMany("Questions")
                        .HasForeignKey("ToeicAudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WordWave.Domain.Models.ToeicPart", "Part")
                        .WithMany("Questions")
                        .HasForeignKey("ToeicPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordWave.Domain.Models.ToeicPassage", "Passage")
                        .WithMany("Questions")
                        .HasForeignKey("ToeicPassageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Audio");

                    b.Navigation("Part");

                    b.Navigation("Passage");
                });

            modelBuilder.Entity("WordWave.Domain.Models.GrammarLesson", b =>
                {
                    b.Navigation("GrammarExamples");
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicAudio", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicPart", b =>
                {
                    b.Navigation("Audios");

                    b.Navigation("Passages");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicPassage", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("WordWave.Domain.Models.ToeicTest", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
